In [4]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]], dtype=float)
print(arr)
print(arr.astype(bool))

[[1. 2. 3.]
 [4. 5. 6.]]
[[ True  True  True]
 [ True  True  True]]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
b=np.insert(arr, 2, 55,axis=0)
print(b)


[1 2 3 4 5]
[ 1  2 55  3  4  5]


In [9]:
import numpy as np
a=np.arange(0,100,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [37]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=(a*b)
print(c)

[ 4 10 18]


In [20]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
c = False  
for x in a:
    if x == 5:
        c = True
        break  
if c:
    print("present")
else:
    print("not")


[1 2 3]
not
